# Generated by Django 3.2 on 2021-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='level_important',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='statement',
            name='success',
            field=models.CharField(choices=[(1, 'Process'), (2, 'Confirmed'), (3, 'Rejected'), (4, 'Returned')], default='Process', max_length=10),
        ),
    ]
