# Generated by Django 3.2 on 2021-04-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20210426_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_at']},
        ),
    ]
